version: 2
jobs:
  Unit Test:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s unit
  Compatibility Test 3.12.0:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s compatibility
  Compatibility Test 3.11.6:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s compatibility
  Compatibility Test 3.10:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s compatibility
  Compatibility Test 3.9:
    docker:
      - image: cimg/python:3.9.10
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s compatibility
  Lint:
    docker:
      - image: cimg/python:3.12.0
    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s lint
  Type Check:
    docker:
      - image: cimg/python:3.12.0

    steps:
      - checkout
      - run:
          command: |
            pip install virtualenv
            pip install nox
            nox -f noxfile.py -s type_check
  Release:
    docker:
      - image: cimg/python:3.12.0

    steps:
      - checkout
      - run:
         command: |
          pip install --upgrade twine
          pip install --upgrade wheel
          pip install --upgrade setuptools
          source twine_upload.sh


workflows:
  version: 2
  test:
    jobs:
      - Lint
      - Unit Test
      - Type Check
      - Compatibility Test 3.12
      - Compatibility Test 3.11
      - Compatibility Test 3.10
      - Compatibility Test 3.9
  release:
    jobs:
      - Release:
          filters:
            # Runs for no branches and only for tags like "1.2.3"
            branches:
              ignore: /.*/
            tags:
              only:
                - /^\d+\.\d+\.\d+$/
